import { UniversityLogo } from './types';

export const providerMeta: Record<
  string,
  { name: string; flag: string; country: string; description: string; website: string }
> = {
  germany: {
    name: 'Germany',
    flag: '🇩🇪',
    country: 'Germany',
    description: 'Germany offers numerous scholarships through DAAD, including EPOS and Leadership for Africa, plus Studienstiftung and university-specific programmes. Public universities charge no tuition for most programmes.',
    website: 'https://www.daad.de',
  },
  japan: {
    name: 'Japan',
    flag: '🇯🇵',
    country: 'Japan',
    description: 'Japan offers MEXT scholarships covering tuition, monthly stipend, and airfare, plus JASSO awards and Japan-funded global development scholarships such as ADB-Japan and JJ/WBGSP.',
    website: 'https://www.mext.go.jp',
  },
  turkey: {
    name: 'Turkey',
    flag: '🇹🇷',
    country: 'Turkey',
    description: 'Türkiye Burslari is the Turkish government\'s comprehensive scholarship programme offering tuition, monthly stipend, accommodation, health insurance, and flights for associate degree through PhD studies across 200+ Turkish universities.',
    website: 'https://www.turkiyeburslari.gov.tr',
  },
  'united-kingdom': {
    name: 'United Kingdom',
    flag: '🇬🇧',
    country: 'United Kingdom',
    description: 'The UK offers world-class scholarships including Chevening (government-funded Master\'s), Gates Cambridge, Clarendon Fund (Oxford), and the Rhodes Scholarship — among the most prestigious international scholarships globally.',
    website: 'https://www.chevening.org',
  },
  australia: {
    name: 'Australia',
    flag: '🇦🇺',
    country: 'Australia',
    description: 'Australia Awards are prestigious, transformational scholarships and short courses offered by the Australian Government to emerging leaders from developing countries for study, research and professional development in Australia.',
    website: 'https://www.australiaawardsindonesia.org',
  },
  'south-korea': {
    name: 'South Korea',
    flag: '🇰🇷',
    country: 'South Korea',
    description: 'South Korea offers the Global Korea Scholarship (GKS) for undergraduate and graduate degrees at Korean universities, plus KOICA scholarships for public sector professionals from developing countries.',
    website: 'https://www.studyinkorea.go.kr',
  },
  singapore: {
    name: 'Singapore',
    flag: '🇸🇬',
    country: 'Singapore',
    description: 'Singapore offers prestigious scholarships through NUS, NTU, and A*STAR, including the Singapore International Graduate Award (SINGA) for PhD studies and ASEAN Undergraduate Scholarships.',
    website: 'https://www.a-star.edu.sg/scholarships',
  },
  france: {
    name: 'France',
    flag: '🇫🇷',
    country: 'France',
    description: 'France offers the Eiffel Excellence Scholarship (government-funded), plus university-specific scholarships at Paris-Saclay, Sciences Po, and ENS Lyon for Master\'s and PhD studies.',
    website: 'https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence',
  },
  canada: {
    name: 'Canada',
    flag: '🇨🇦',
    country: 'Canada',
    description: 'Canada offers the CGRS-D and Impact+ research awards administered by CIHR/NSERC/SSHRC, the Lester B. Pearson Scholarship at University of Toronto, and the Canada Postdoctoral Research Award (CPRA) for postdoctoral researchers.',
    website: 'https://nserc-crsng.canada.ca',
  },
  'united-states': {
    name: 'United States',
    flag: '🇺🇸',
    country: 'United States',
    description: 'The US offers Fulbright/AMINEF awards for Indonesian citizens plus global university scholarships such as Stanford\'s Knight-Hennessy Scholars for full-time graduate study.',
    website: 'https://www.aminef.or.id',
  },
  netherlands: {
    name: 'Netherlands',
    flag: '🇳🇱',
    country: 'Netherlands',
    description: 'The Netherlands offers the NL Scholarship and university-specific excellence awards at TU Delft, Amsterdam, Groningen, Leiden, Maastricht, Radboud, and VU Amsterdam. Older OKP rounds have ended, so current applicants should check active alternatives.',
    website: 'https://www.studyinnl.org/finances/scholarships',
  },
  belgium: {
    name: 'Belgium',
    flag: '🇧🇪',
    country: 'Belgium',
    description: 'Belgium offers VLIR-UOS ICP Connect Scholarships for students from 29 developing countries including Indonesia, available at bachelor, initial master, and advanced master levels across Flemish universities.',
    website: 'https://www.vliruos.be/get-funded/study-scholarships',
  },
  eu: {
    name: 'European Union',
    flag: '🇪🇺',
    country: 'European Union',
    description: 'Erasmus Mundus Joint Master (EMJM) is a prestigious EU-funded scholarship for 1-2 year master\'s degrees jointly delivered by at least 3 universities in 3+ European countries. Full scholarships cover tuition, living allowance, travel, and insurance for 150+ programmes.',
    website: 'https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters',
  },
  china: {
    name: 'China',
    flag: '🇨🇳',
    country: 'China',
    description: 'China offers the Chinese Government Scholarship (CGS) through CSC for bachelor to PhD studies at 274+ universities, plus Belt and Road and MOFCOM scholarships for partner countries.',
    website: 'http://studyinchina.csc.edu.cn/',
  },
  sweden: {
    name: 'Sweden',
    flag: '🇸🇪',
    country: 'Sweden',
    description: 'The Swedish Institute offers fully funded SISGP master\'s scholarships for professionals from 34 developing countries, plus the Pioneering Women in STEM scholarship for women in STEM fields.',
    website: 'https://si.se/en/apply/scholarships/',
  },
  italy: {
    name: 'Italy',
    flag: '🇮🇹',
    country: 'Italy',
    description: 'Italy offers MAECI government scholarships, Invest Your Talent in Italy (IYT), and Special Projects scholarships for foreign students at Italian universities, covering tuition and monthly allowances.',
    website: 'https://studyinitaly.esteri.it/',
  },
  hungary: {
    name: 'Hungary',
    flag: '🇭🇺',
    country: 'Hungary',
    description: 'Stipendium Hungaricum offers fully funded bachelor\'s, master\'s, and doctoral studies at Hungarian universities for citizens of 70+ partner countries including Indonesia, covering tuition, stipend, accommodation, and insurance.',
    website: 'https://stipendiumhungaricum.hu/',
  },
  taiwan: {
    name: 'Taiwan',
    flag: '🇹🇼',
    country: 'Taiwan',
    description: 'Taiwan offers MOE scholarships (tuition + stipend), TaiwanICDF (fully funded with housing), Huayu (language study), plus university-specific awards at NTU and NTHU for bachelor to PhD studies.',
    website: 'https://english.moe.gov.tw',
  },
  switzerland: {
    name: 'Switzerland',
    flag: '🇨🇭',
    country: 'Switzerland',
    description: 'Switzerland offers the Swiss Government Excellence Scholarships (CHF 2,450/month), ETH Zurich ESOP (CHF 12,000/semester), EPFL Excellence Fellowships, and the University of Geneva Excellence Master Fellowships for Master\'s and PhD studies at world-leading institutions.',
    website: 'https://www.sbfi.admin.ch/en/swiss-government-excellence-scholarships',
  },
  austria: {
    name: 'Austria',
    flag: '🇦🇹',
    country: 'Austria',
    description: 'Austria offers OeAD-managed scholarships (Ernst Mach Worldwide, Ernst Mach UAS, Follow-Up, and Franz Werfel) for Master\'s, PhD, and postdoc research stays, plus the Helmut Veith Stipend at TU Wien for Computer Science Master\'s students.',
    website: 'https://oead.at/en/to-austria/scholarships/',
  },
  finland: {
    name: 'Finland',
    flag: '🇫🇮',
    country: 'Finland',
    description: 'Finland offers fully funded international Master scholarships at the University of Helsinki, Aalto, Tampere, Oulu, and Hanken (Swan and Eduard Swan), plus the Nokia Foundation Scholarship (EUR 10,000/year) for ICT, CS, and STEM Master\'s and PhD students.',
    website: 'https://www.studyinfinland.fi/scholarships',
  },
  'new-zealand': {
    name: 'New Zealand',
    flag: '🇳🇿',
    country: 'New Zealand',
    description: 'Manaaki New Zealand Scholarships are fully funded for citizens of developing countries including Indonesia, covering tuition, living allowance, airfare, and insurance for undergraduate through PhD studies.',
    website: 'https://www.nzscholarships.govt.nz/',
  },
  ireland: {
    name: 'Ireland',
    flag: '🇮🇪',
    country: 'Ireland',
    description: 'Ireland offers GOI-IES (tuition + EUR 10,000 for one year), GOIPG (up to EUR 34,000/year for PhD), plus university scholarships at Trinity College Dublin and UCD.',
    website: 'https://hea.ie/',
  },
  denmark: {
    name: 'Denmark',
    flag: '🇩🇰',
    country: 'Denmark',
    description: 'Denmark offers government scholarships (tuition waivers + DKK 7,000/month living grant) administered by individual universities for non-EU/EEA Master\'s students.',
    website: 'https://studyindenmark.dk/study-options/scholarships',
  },
  norway: {
    name: 'Norway',
    flag: '🇳🇴',
    country: 'Norway',
    description: 'Norway offers tuition-free education at public universities for ALL international students. PhD positions are fully salaried. BI Norwegian Business School offers the Presidential Scholarship with full tuition + stipend.',
    website: 'https://www.studyinnorway.no/',
  },
  'hong-kong': {
    name: 'Hong Kong',
    flag: '🇭🇰',
    country: 'Hong Kong',
    description: 'Hong Kong offers the HKPFS (400 PhD fellowships at HK$28,400/month) and HKU Entrance Scholarships (full tuition + living allowance) at 8 world-class universities.',
    website: 'https://www.ugc.edu.hk/en/non-local-students/hong-kong-phd-fellowship-scheme.html',
  },
  malaysia: {
    name: 'Malaysia',
    flag: '🇲🇾',
    country: 'Malaysia',
    description: 'The Malaysia International Scholarship (MIS) covers tuition, MYR 1,500/month stipend, insurance, airfare, and thesis costs for Master\'s and PhD studies at Malaysian universities.',
    website: 'https://biasiswa.mohe.gov.my/INTER/index.php',
  },
  poland: {
    name: 'Poland',
    flag: '🇵🇱',
    country: 'Poland',
    description: 'Poland offers the NAWA Stefan Banach (fully funded Master\'s for 36 partner countries including Indonesia) and Ignacy Łukasiewicz programmes (STEM), plus university-specific scholarships at Jagiellonian (Kraków) and University of Warsaw.',
    website: 'https://nawa.gov.pl/en/',
  },
  spain: {
    name: 'Spain',
    flag: '🇪🇸',
    country: 'Spain',
    description: 'Spain offers MAEC-AECID scholarships for citizens of Spanish cooperation partner countries (incl. Indonesia for select programs), "la Caixa" INPhINIT and Junior Leader fellowships (€35,800/yr PhD, €106,700/yr postdoc), and the IE Foundation Fellows Program at IE University.',
    website: 'https://www.aecid.es/en/',
  },
  romania: {
    name: 'Romania',
    flag: '🇷🇴',
    country: 'Romania',
    description: 'Romania offers MFA scholarships (Non-EU citizens) covering tuition, monthly stipend, and a Romanian language preparatory year; the ARICE programme (40 seats/year, non-EU/EFTA only) with full funding; plus university-specific awards at Transilvania University of Brașov (TAS, 800 lei/month) and West University of Timișoara (WUT for EU Third Countries).',
    website: 'https://scholarships.studyinromania.gov.ro/',
  },
  russia: {
    name: 'Russia',
    flag: '🇷🇺',
    country: 'Russia',
    description: 'Russia offers the Open Doors Russian Scholarship Project (24+ leading universities, online Olympiad), the Russian Government Quota via Rossotrudnichestvo (15,000 seats/year, 180+ countries), the SPbU Open International Olympiad, federal university olympiads (BMSTU, NUST MISIS, MIPT, MIFI, Ural Federal), MGIMO state-funded places, and the HSE International Olympiad (incl. joint Skoltech Math of Machine Learning track).',
    website: 'https://education-in-russia.com/',
  },
  'saudi-arabia': {
    name: 'Saudi Arabia',
    flag: '🇸🇦',
    country: 'Saudi Arabia',
    description: 'Saudi Arabia offers fully funded government scholarships through 27 public universities including King Saud University (KSU), King Abdulaziz University (KAU), KFUPM, Umm Al-Qura, Islamic University of Madinah, and KAUST. Benefits include full tuition, housing, monthly stipend, health insurance, and annual flights under Saudi Vision 2030.',
    website: 'https://studyinsaudi.moe.gov.sa',
  },
  qatar: {
    name: 'Qatar',
    flag: '🇶🇦',
    country: 'Qatar',
    description: 'Qatar offers fully funded scholarships through Qatar University (QU), Hamad Bin Khalifa University (HBKU / Qatar Foundation), Doha Institute, and the Education Above All (EAA) programme, covering tuition, housing, monthly stipends, and flights for international students.',
    website: 'https://www.qu.edu.qa',
  },
};
