interface Env {
  ASSETS: {
    fetch: (request: Request | string, init?: RequestInit) => Promise<Response>;
  };
  DB: any;
  [key: string]: any;
}

export default {
  async fetch(request: Request, env: Env, ctx: any): Promise<Response> {
    const url = new URL(request.url);
    const pathname = url.pathname;

    // 1. First, try fetching directly from ASSETS (handles _next/static, public images, icons, etc.)
    try {
      const assetRes = await env.ASSETS.fetch(request);
      if (assetRes.status !== 404) {
        return assetRes;
      }
    } catch {
      // Continue to path resolution
    }

    // 2. Resolve HTML paths generated by Next.js in .next/server/app/
    const possiblePaths: string[] = [];

    if (pathname === '/' || pathname === '') {
      possiblePaths.push('/server/app/index.html');
    } else {
      const cleanPath = pathname.replace(/\/$/, '');

      // Check direct HTML match (e.g. /about -> /server/app/about.html)
      possiblePaths.push(`/server/app${cleanPath}.html`);
      possiblePaths.push(`/server/app${cleanPath}/index.html`);

      // Check special Next.js routes (robots.txt, sitemap.xml)
      if (cleanPath === '/robots.txt') {
        possiblePaths.push('/server/app/robots.txt.body');
      } else if (cleanPath === '/sitemap.xml') {
        possiblePaths.push('/server/app/sitemap.xml.body');
      }
    }

    for (const pathCandidate of possiblePaths) {
      try {
        const candidateUrl = new URL(pathCandidate, url.origin);
        const res = await env.ASSETS.fetch(new Request(candidateUrl, request));
        if (res.status === 200) {
          const headers = new Headers(res.headers);
          if (pathCandidate.endsWith('.html')) {
            headers.set('Content-Type', 'text/html; charset=utf-8');
          } else if (pathCandidate.includes('sitemap.xml')) {
            headers.set('Content-Type', 'application/xml; charset=utf-8');
          } else if (pathCandidate.includes('robots.txt')) {
            headers.set('Content-Type', 'text/plain; charset=utf-8');
          }
          return new Response(res.body, {
            status: 200,
            headers,
          });
        }
      } catch {
        // Try next candidate
      }
    }

    // 3. Fallback to 404 page generated by Next.js
    try {
      const notFoundUrl = new URL('/server/app/_not-found.html', url.origin);
      const notFoundRes = await env.ASSETS.fetch(new Request(notFoundUrl, request));
      if (notFoundRes.status === 200) {
        const headers = new Headers(notFoundRes.headers);
        headers.set('Content-Type', 'text/html; charset=utf-8');
        return new Response(notFoundRes.body, {
          status: 404,
          headers,
        });
      }
    } catch {
      // Fall through to generic 404
    }

    return new Response('Page Not Found', { status: 404 });
  },
};
